### ISSUE TITLE
Git tag for this forked repository

### ISSUE THREAD

**Issue by PeterDaveHello** [dpup/freemail#8]
The current [tags](https://github.com/dpup/freemail/tags) are from the [upstream repository](https://github.com/willwhite/freemail), it'll be great if we can have some git tags for this forked golang version(and maybe delete the old one to prevent confusion), so that we can reference the project properly(instead of using master branch directly).

Thank you!

**Comment by dpup** [comment]
Weirdly only just saw this issue. Apologies for that. I recently added. v1.6.1 but it's a good call to cleanup the old ones or perhaps start afresh at v2.0.0

**Comment by dpup** [comment]
Cleanup done.

**Comment by PeterDaveHello** [comment]
Thanks @dpup 🎉
